baseURL = "https://liuzouyuan.cn"
title = "liuzouyuan.cn"
theme = "haofuza"
hasCJKLanguage = true
timeout = 600000

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
  [markup.highlight]
    style = 'manni'